branch-defaults:
  default:
    environment: Myapplication-env
environment-defaults:
  Myapplication-env:
    branch: null
    repository: null
global:
  application_name: myapplication
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-2::platform/Java 8 running
    on 64bit Amazon Linux/2.8.2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
deploy:
  artifact: target/myapplication-eb.jar
